services:
  # frontend-prod:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - cell-counter

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  cell-counter:
    build:
      context: ./cell-counter-yolov4
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./cell-counter-yolov4:/app
    environment:
      - PYTHONUNBUFFERED=1

  cell-counter-v8:
    build:
      context: ./cell-counter-yolov8
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./cell-counter-yolov8:/app
    environment:
      - PYTHONUNBUFFERED=1