services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  cell-counter-v8:
    build:
      context: ./backend/cell-counter-yolov8
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend/cell-counter-yolov8:/app
    environment:
      - PYTHONUNBUFFERED=1

  cell-counter-cuda:
    build:
      context: ./backend/cell-counter-cuda
      dockerfile: Dockerfile
    gpus: all
    ports:
      - "8003:8003"
    volumes:
      - ./backend/cell-counter-cuda:/app
    environment:
      - PYTHONUNBUFFERED=1